language: php

php:
  - '7.0'

sudo: false
services:
  - mysql
before_install:
  - mysql -u root --default-character-set=utf8 < sql/chartBlank.sql
before_script: 
  - composer require  setasign/fpdi-fpdf ^2.0
