language: php

php:
  - 5.6

script: phpunit

sudo: false
services:
  - mysql
before_install:
  - mysql -u root --default-character-set=utf8 < sql/chartBlank.sql
before_script: 
  - composer require  setasign/fpdf ^1.8
  - composer require  setasign/fpdi ^2.0
